# Generated by Django 5.1 on 2026-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('author', models.CharField(max_length=255, verbose_name='Auteur')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Editeur')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Annee de publication')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Genre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name="Nombre total d'exemplaires")),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Exemplaires disponibles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-created_at'],
            },
        ),
    ]
