# Generated by Django 5.1 on 2026-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID Utilisateur')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Utilisateur')),
                ('book_id', models.IntegerField(verbose_name='ID Livre')),
                ('book_title', models.CharField(blank=True, max_length=255, verbose_name='Titre du livre')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('due_date', models.DateTimeField(verbose_name='Date de retour prevue')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effectif')),
                ('status', models.CharField(choices=[('ACTIVE', 'En cours'), ('RETURNED', 'Retourne'), ('LATE', 'En retard')], default='ACTIVE', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
